#ifndef FTS_H
#define FTS_H

#define LETTER_WIDTH 8
#define BORDER_THICKNESS 2
#define TRUE_LETTER_WIDTH ((LETTER_WIDTH) + (BORDER_THICKNESS))
#define TRUE_LETTER_HEIGHT ((LETTER_HEIGHT) + (BORDER_THICKNESS))
#define LETTER_HEIGHT 13

extern const char Classic[][TRUE_LETTER_HEIGHT][TRUE_LETTER_WIDTH];

#endif
