#include "snakeDrawings.h"
#include "./../snake.h"
#include "./../../window/window.h"
#define E (MAX_SNAKE_COLORS - 1)
#define B 0
#define APPLE_BROWN 0xFF452C09
#define APPLE_RED 0xFFba2709
#define APPLE_GREEN 0xFF124F0D
// use E to represent EYE, B to represent BACKGROUND. Longer definitions not used so as not to deform arrays (makes editing and viewing simpler)
char classicHeadUp[DRAW_SIZE][DRAW_SIZE] = {
    {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
    {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
    {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
    {1, 1, 1, E, 1, 1, 1, 1, E, 1, 1, 1},
    {1, 1, E, E, 1, 1, 1, 1, E, E, 1, 1},
    {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
    {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
    {2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2},
    {2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2},
    {1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1},
    {1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1},
    {1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1}};
char classicOther[DRAW_SIZE][DRAW_SIZE] = {
    {1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1},
    {1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1},
    {1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1},
    {1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1},
    {1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1},
    {1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1},
    {1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1},
    {1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1},
    {1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1},
    {1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1},
    {1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1},
    {1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1}};
char classicTurn[DRAW_SIZE][DRAW_SIZE] = {
    {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
    {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
    {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
    {1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2},
    {1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1},
    {1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1},
    {1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1},
    {1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1},
    {1, 1, 1, 2, 1, 1, 1, 1, 2, 2, 2, 2},
    {1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1},
    {1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1},
    {1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1}};
char classicTail[DRAW_SIZE][DRAW_SIZE] = {
    {1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 1},
    {1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1, B},
    {B, 1, 2, 1, 1, 2, 1, 2, 1, 1, B, B},
    {B, 1, 1, 2, 1, 2, 1, 2, 1, B, B, B},
    {B, 1, 1, 1, 2, 1, 2, 2, B, B, B, B},
    {B, B, B, 1, 1, 2, 2, 2, 1, B, B, B},
    {B, B, B, B, B, 1, 2, 1, 1, B, B, B},
    {B, B, B, B, B, B, 1, 2, 1, B, B, B},
    {B, B, B, B, B, B, 1, 2, 1, B, B, B},
    {B, B, B, B, B, 1, 2, 1, B, B, B, B},
    {B, B, B, B, B, 1, 1, B, B, B, B, B},
    {B, B, B, B, B, 1, 1, B, B, B, B, B}};
HexColor appleColorMap[] = {0x00000000, APPLE_RED, APPLE_BROWN, APPLE_GREEN};
char classicApple[DRAW_SIZE][DRAW_SIZE] = {
    {B, B, B, B, B, B, B, 3, 2, B, B, B},
    {B, B, B, B, B, B, 3, 2, 3, B, B, B},
    {B, B, B, B, 1, B, 2, 1, B, B, B, B},
    {B, B, B, 1, 1, 1, 1, 1, 1, B, B, B},
    {B, B, B, 1, 1, 1, 1, 1, 1, B, B, B},
    {B, B, B, 1, 1, 1, 1, 1, 1, B, B, B},
    {B, B, B, 1, 1, 1, 1, 1, 1, B, B, B},
    {B, B, B, 1, 1, 1, 1, 1, 1, B, B, B},
    {B, B, B, 1, 1, 1, 1, 1, 1, B, B, B},
    {B, B, B, B, 1, B, B, 1, B, B, B, B},
    {B, B, B, B, B, B, B, B, B, B, B, B},
    {B, B, B, B, B, B, B, B, B, B, B, B}};
char background[DRAW_SIZE][DRAW_SIZE] = {
    {B, B, B, B, B, B, B, B, B, B, B, B},
    {B, B, B, B, B, B, B, B, B, B, B, B},
    {B, B, B, B, B, B, B, B, B, B, B, B},
    {B, B, B, B, B, B, B, B, B, B, B, B},
    {B, B, B, B, B, B, B, B, B, B, B, B},
    {B, B, B, B, B, B, B, B, B, B, B, B},
    {B, B, B, B, B, B, B, B, B, B, B, B},
    {B, B, B, B, B, B, B, B, B, B, B, B},
    {B, B, B, B, B, B, B, B, B, B, B, B},
    {B, B, B, B, B, B, B, B, B, B, B, B},
    {B, B, B, B, B, B, B, B, B, B, B, B},
    {B, B, B, B, B, B, B, B, B, B, B, B}};
char goomba[BIG_DRAW_SIZE][BIG_DRAW_SIZE] = {
    {B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B},
    {B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B},
    {B, B, B, B, B, B, B, B, B, 1, 1, 1, 1, 1, 1, B, B, B, B, B, B, B, B, B},
    {B, B, B, B, B, B, B, B, 1, 1, 1, 1, 1, 1, 1, 1, 1, B, B, B, B, B, B, B},
    {B, B, B, B, B, B, B, B, 1, 1, 1, 1, 1, 1, 1, 1, 1, B, B, B, B, B, B, B},
    {B, B, B, B, B, B, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, B, B, B, B, B, B},
    {B, B, B, B, B, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, B, B, B, B},
    {B, B, B, B, B, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, B, B, B, B},
    {B, B, B, 1, 1, 4, 4, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 4, 4, 1, B, B, B},
    {B, B, 1, 1, 1, 1, E, E, 4, 1, 1, 1, 1, 1, 1, 4, 4, E, 1, 1, 1, 1, 1, B},
    {B, B, 1, 1, 1, 1, E, E, 4, 4, 4, 4, 4, 4, 4, 4, 4, E, 1, 1, 1, 1, 1, B},
    {B, B, 1, 1, 1, 1, E, E, 4, 4, 4, 4, 4, 4, 4, 4, 4, E, 1, 1, 1, 1, 1, B},
    {1, 1, 1, 1, 1, 1, E, E, 4, E, E, 1, 1, 1, E, 4, 4, E, 1, 1, 1, 1, 1, 1},
    {1, 1, 1, 1, 1, 1, E, E, E, E, E, 1, 1, 1, E, E, E, E, 1, 1, 1, 1, 1, 1},
    {1, 1, 1, 1, 1, 1, E, E, E, E, E, 1, 1, 1, E, E, E, E, 1, 1, 1, 1, 1, 1},
    {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
    {B, B, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, B},
    {B, B, B, B, B, B, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, B, B, B, B, B, B},
    {B, B, B, B, B, B, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, B, B, B, B, B, B},
    {B, B, B, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, B, B, B},
    {B, B, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, B},
    {B, B, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, B},
    {B, B, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, B},
    {B, B, B, 2, 2, 2, 2, 2, 2, 2, 2, B, B, B, 2, 2, 2, 2, 2, 2, 2, B, B, B}};
HexColor marioItemColorMap[] = {0x00000000, 0xffff0204, 0xff612210, 0xffe9a24a, 0xff0f437e, 0xfff7fd17, 0xff5c656c, 0xFF000000};
char marioItem[BIG_DRAW_SIZE][BIG_DRAW_SIZE] = {{B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B},
                                                {B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B},
                                                {B, B, B, B, B, B, B, 1, 1, 1, 1, 1, 1, 1, 1, B, B, B, B, B, B, B, B, B},
                                                {B, B, B, B, B, B, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, B, B, B, B},
                                                {B, B, B, B, B, B, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, B, B, B, B},
                                                {B, B, B, B, B, B, 2, 2, 2, 2, 3, 3, 3, 3, 7, 3, 3, B, B, B, B, B, B, B},
                                                {B, B, B, B, 2, 2, 3, 2, 2, 3, 3, 3, 3, 3, 7, 3, 3, 3, 3, 3, B, B, B, B},
                                                {B, B, B, B, 2, 2, 3, 2, 2, 2, 3, 3, 3, 3, 3, 2, 2, 3, 3, 3, 3, 3, B, B},
                                                {B, B, B, B, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, B, B, B, B},
                                                {B, B, B, B, B, B, B, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, B, B, B, B, B, B},
                                                {B, B, B, B, B, B, B, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, B, B, B, B, B, B},
                                                {B, B, B, B, B, B, 1, 1, 1, 4, 1, 1, 1, 1, 1, B, B, B, B, B, B, B, B, B},
                                                {B, B, B, B, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, B, B, B, B},
                                                {B, B, 1, 1, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 1, 1, 1, 1, 1, 1, 1, B, B},
                                                {B, B, 3, 3, 3, 3, 1, 4, 4, 5, 4, 4, 4, 4, 5, 4, 4, 1, 3, 3, 3, 3, B, B},
                                                {B, B, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, B, B},
                                                {B, B, 3, 3, 3, 3, 6, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 3, 3, 3, 3, B, B},
                                                {B, B, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, B, B},
                                                {B, B, B, B, B, B, 4, 4, 4, 4, B, B, B, 4, 4, 4, 4, 4, B, B, B, B, B, B},
                                                {B, B, B, B, 2, 2, 2, 2, 2, B, B, B, B, B, B, 2, 2, 2, 2, 2, B, B, B, B},
                                                {B, B, 2, 2, 2, 2, 2, 2, 2, B, B, B, B, B, B, 2, 2, 2, 2, 2, 2, 2, B, B},
                                                {B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B},
                                                {B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B},
                                                {B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B}};
char pipe[BIG_DRAW_SIZE][BIG_DRAW_SIZE] = {{B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, 1, 1, 1, 1, 1},
                                           {B, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2},
                                           {B, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2},
                                           {B, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2},
                                           {B, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2},
                                           {B, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2},
                                           {B, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2},
                                           {B, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2},
                                           {B, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2},
                                           {B, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2},
                                           {B, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2},
                                           {B, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2},
                                           {B, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, B, B, B, B, B, B, B, B, 1, 2, 2, 2, 2},
                                           {B, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, B, B, B, B, B, B, B, B, B, B, B, B, B},
                                           {B, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, B, B, B, B, B, B, B, B, B, B, B, B, B},
                                           {B, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, B, B, B, B, B, B, B, B, B, B, B, B, B},
                                           {B, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, B, B, B, B, B, B, B, B, B, B, B, B, B},
                                           {B, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, B, B, B, B, B, B, B, B, B, B, B, B, B},
                                           {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, B, B, B, B, B, B, B, B, B, B, B, B},
                                           {1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, B, B, B, B, B, B, B, B, B, B, B, B},
                                           {1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, B, B, B, B, B, B, B, B, B, B, B, B},
                                           {1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, B, B, B, B, B, B, B, B, B, B, B, B},
                                           {1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, B, B, B, B, B, B, B, B, B, B, B, B},
                                           {1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, B, B, B, B, B, B, B, B, B, B, B, B}};
HexColor excaliburColorMap[] = {0x00000000, 0xffd4a937, 0xff000000, 0xffe3cc78, 0xffab4c30, 0xff7a3321, 0xffa4852a, 0xff251110, 0xff55342f, 0xff5b6483, 0xff7e83a4, 0xffc2c4d3, 0xffa5a8bd, 0xff999eb4, 0xff434b62};
char excalibur[BIG_DRAW_SIZE][BIG_DRAW_SIZE] = {{B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B},
                                                {B, B, B, B, B, B, B, B, B, B, B, 1, 2, 3, B, B, B, B, B, B, B, B, B, B},
                                                {B, B, B, B, B, B, B, B, B, B, 2, 4, 5, 4, 2, B, B, B, B, B, B, B, B, B},
                                                {B, B, B, B, B, B, B, B, B, B, B, 2, 6, 2, B, B, B, B, B, B, B, B, B, B},
                                                {B, B, B, B, B, B, B, B, B, B, B, 2, 7, 2, B, B, B, B, B, B, B, B, B, B},
                                                {B, B, B, B, B, B, B, B, B, B, B, 2, 8, 2, B, B, B, B, B, B, B, B, B, B},
                                                {B, B, B, B, B, B, B, B, B, B, B, 2, 2, 2, B, B, B, B, B, B, B, B, B, B},
                                                {B, B, B, B, B, B, 3, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 3, B, B, B, B, B},
                                                {B, B, B, B, B, B, B, B, B, B, B, 9, 2, 10, B, B, B, B, B, B, B, B, B, B},
                                                {B, B, B, B, B, B, B, B, B, B, B, 10, 11, 12, B, B, B, B, B, B, B, B, B, B},
                                                {B, B, B, B, B, B, B, B, B, B, B, 10, 11, 12, B, B, B, B, B, B, B, B, B, B},
                                                {B, B, B, B, B, B, B, B, B, B, B, 10, 11, 12, B, B, B, B, B, B, B, B, B, B},
                                                {B, B, B, B, B, B, B, B, B, B, B, 10, 11, 12, B, B, B, B, B, B, B, B, B, B},
                                                {B, B, B, B, B, B, B, B, B, B, B, 10, 11, 12, B, B, B, B, B, B, B, B, B, B},
                                                {B, B, B, B, B, B, B, B, B, B, B, 10, 11, 12, B, B, B, B, B, B, B, B, B, B},
                                                {B, B, B, B, B, B, B, B, B, B, B, 10, 11, 12, B, B, B, B, B, B, B, B, B, B},
                                                {B, B, B, B, B, B, B, B, B, B, B, 10, 11, 12, 12, 12, 12, 2, B, B, B, B, B, B},
                                                {B, B, B, 2, 10, 12, 10, 10, 10, 10, 10, 9, 11, 10, 10, 10, 10, 10, 10, 12, 10, B, B, B},
                                                {B, B, B, 10, 10, 10, 13, 13, 13, 13, 13, 10, 10, 10, 13, 13, 13, 13, 13, 14, 14, 14, B, B},
                                                {B, B, 2, 10, 10, 10, 10, 10, 10, 13, 13, 13, 13, 13, 13, 9, 9, 14, 14, 14, 14, 14, 14, B},
                                                {B, B, 10, 10, 10, 10, 10, 10, 10, 10, 10, 9, 9, 9, 9, 9, 9, 9, 14, 14, 14, 14, 14, 2},
                                                {B, 2, 9, 10, 10, 10, 10, 10, 10, 10, 10, 9, 9, 9, 9, 9, 9, 9, 14, 14, 14, 14, B, B},
                                                {B, B, 2, 10, 10, 10, 10, 10, 10, 13, 13, 9, 9, 9, 9, 9, 9, 9, 14, 14, 2, B, B, B},
                                                {B, B, B, B, B, B, B, B, 2, 13, 9, 9, 9, 9, 9, 9, 2, 2, B, B, B, B, B, B}};
char stone[BIG_DRAW_SIZE][BIG_DRAW_SIZE] = {{B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B},
                                            {B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B},
                                            {B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B},
                                            {B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B},
                                            {B, B, B, B, B, B, B, B, B, B, B, 1, 2, 3, 2, 1, B, B, B, B, B, B, B, B},
                                            {B, B, B, B, B, B, B, B, B, B, 1, 3, 4, 2, 3, 3, 1, B, B, B, B, B, B, B},
                                            {B, B, B, B, B, B, B, B, B, B, 1, 2, 2, 1, 2, 4, 2, B, B, B, B, B, B, B},
                                            {B, B, B, B, B, B, B, B, B, 1, 1, 1, 1, 1, 1, 2, 2, 1, B, B, B, B, B, B},
                                            {B, B, B, B, B, B, B, B, 1, 4, 2, 2, 2, 1, 1, 2, 2, 2, 1, B, B, B, B, B},
                                            {B, B, B, B, B, B, B, 1, 1, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, B, B, B, B, B},
                                            {B, B, B, B, B, B, B, 1, 2, 2, 2, 1, 2, 1, 1, 1, 1, 1, 2, B, B, B, B, B},
                                            {B, B, B, B, B, B, B, 1, 1, 1, 1, 1, 3, 3, 2, 1, 1, 1, 2, 1, B, B, B, B},
                                            {B, B, B, B, B, B, B, 1, 1, 1, 1, 3, 2, 2, 3, 2, 1, 1, 1, 1, B, B, B, B},
                                            {B, B, B, B, B, B, 1, 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 1, B, B, B, B},
                                            {B, B, B, B, B, 3, 1, 3, 2, 1, 2, 2, 3, 3, 2, 2, 2, 1, 1, 1, B, B, B, B},
                                            {B, B, B, B, B, 1, 3, 2, 1, 1, 1, 1, 4, 2, 3, 1, 2, 1, 1, 3, 1, B, B, B},
                                            {B, B, B, B, 1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 1, 1, 1, 2, 3, 1, B, B},
                                            {B, B, B, B, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 2, 2, 1, 1, 4, 1, 2, 1, B, B},
                                            {B, B, B, B, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 3, 1, 1, 1, B, B},
                                            {B, B, B, B, B, B, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, B, B},
                                            {B, B, B, B, B, B, B, B, B, B, 1, 1, 1, 1, 1, 1, 1, 1, B, B, B, B, B, B},
                                            {B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B},
                                            {B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B},
                                            {B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B}};
char catapult[BIG_DRAW_SIZE][BIG_DRAW_SIZE] = {{B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B},
                                               {B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B},
                                               {B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B},
                                               {B, B, B, B, B, B, B, B, B, B, B, B, B, B, 1, B, B, B, B, B, B, B, B, B},
                                               {B, B, B, B, B, B, B, B, 2, 2, B, B, B, B, 1, B, B, B, B, B, B, B, B, B},
                                               {B, B, B, B, B, B, B, B, 2, 2, B, B, B, 2, 1, B, B, B, B, B, B, B, B, B},
                                               {B, B, B, B, B, B, B, 1, 1, 2, B, B, B, 2, 1, B, B, B, B, B, B, B, B, B},
                                               {B, B, B, B, B, B, B, 1, 1, 2, 2, B, B, 2, 1, B, B, B, B, B, B, B, B, B},
                                               {B, B, B, B, B, B, B, B, 1, 1, 2, B, B, B, 1, 1, B, B, B, B, B, B, B, B},
                                               {B, B, B, B, B, B, B, B, 1, 1, 1, B, B, B, 1, 1, B, B, B, B, B, B, B, B},
                                               {B, B, B, B, B, B, B, B, 1, 1, 1, 1, B, B, 1, 1, B, B, B, B, B, B, B, B},
                                               {B, B, B, B, B, B, B, B, B, B, B, 1, 1, B, 1, 1, 1, B, B, B, B, B, B, B},
                                               {B, B, B, B, B, B, 1, 1, B, B, B, B, 1, 1, 1, B, 1, B, B, B, B, B, B, B},
                                               {B, B, B, B, B, B, 1, 1, B, B, B, B, B, 1, 1, B, 1, 1, B, B, B, B, B, B},
                                               {B, B, B, B, B, B, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, B, B, B, B, B, B},
                                               {B, B, B, B, B, B, 1, 2, 1, 1, 1, 1, 1, 1, 1, B, B, 1, B, B, B, B, B, B},
                                               {B, B, B, B, B, B, 1, B, 3, 1, 1, 1, 1, 1, 3, B, 1, 1, 1, B, B, B, B, B},
                                               {B, B, B, B, B, 3, 3, B, 3, 3, 3, 3, 3, 3, 3, B, 3, 3, 3, 3, B, B, B, B},
                                               {B, B, B, B, B, 3, 2, B, 2, 3, 3, 3, 3, 3, 2, B, B, 3, 3, 3, B, B, B, B},
                                               {B, B, B, B, B, 3, 2, B, 2, 3, 3, 3, 3, 3, 2, B, 2, 3, 3, 3, B, B, B, B},
                                               {B, B, B, B, B, B, 3, 2, 3, B, B, B, B, B, 3, B, 4, B, B, B, B, B, B, B},
                                               {B, B, B, B, B, B, B, B, B, B, B, B, B, B, 3, B, B, B, B, B, B, B, B, B},
                                               {B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B},
                                               {B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B}};
char wyvHead[BIG_DRAW_SIZE][BIG_DRAW_SIZE] = {{B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, B, B, 4, 4, B, B, B, B, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 2, 3, 2, 3, 4, B, B, B, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 2, 3, 2, 1, 4, B, B, B, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 4, 2, 2, 1, 3, 2, B, B, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 4, 2, 2, 1, 3, 4, B, B, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 3, 4, 2, 1, 2, 3, B, B, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 3, 2, 2, 1, 1, 4, B, B, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 4, 2, 2, 1, 2, 3, B, B, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 3, 2, 1, 1, 1, 1, 3, B, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 3, 2, 1, 1, 3, 4, 2, 3, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 3, 2, 1, 1, 3, 2, 4, 3, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 3, 1, 1, 1, 3, 3, 2, 4, 2, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, 3, 2, 2, 1, 1, E, 2, 1, 3, 3, 3, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, 3, 2, 2, 1, 1, E, E, 2, 3, 3, 3, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, 3, 2, 2, 1, 1, 2, E, 2, 3, 4, 2, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, 3, 2, 2, 1, 1, 2, 2, 2, 3, 3, 3, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, 3, 2, 2, 1, 1, 2, E, E, 3, 3, 3, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, 3, 3, 3, 1, 1, 1, 2, 2, 3, 4, 3, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, 3, 4, 4, 1, 3, 2, 2, 2, 2, 2, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, 3, 3, 2, 4, 2, 1, 2, 3, 4, 4, 3, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, 3, 3, 4, 1, 3, 1, 1, 3, 3, 3, 3, 2, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, 3, 4, 4, 1, 1, 1, 1, 3, 3, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, 3, 2, 4, 1, 1, 1, 1, 3, 3, B, B, B, B, B, B, B, B}};
char wyvBody[BIG_DRAW_SIZE][BIG_DRAW_SIZE] = {{B, B, B, B, B, B, B, B, 4, 4, 1, 1, 1, 1, 4, 4, 2, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 4, 4, 1, 1, 1, 1, 4, 4, 2, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 2, 4, 1, 1, 1, 1, 4, 4, 2, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 4, 4, 1, 1, 1, 1, 4, 2, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 4, 4, 3, 1, 1, 1, 4, 4, 2, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 4, 4, 3, 1, 1, 1, 4, 4, 2, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 2, 4, 3, 1, 1, 1, 4, 4, 2, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 4, 4, 3, 1, 1, 1, 4, 2, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 4, 4, 3, 1, 1, 1, 4, 2, 4, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 4, 4, 3, 1, 1, 1, 4, 4, 2, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 4, 4, 3, 1, 1, 1, 4, 4, 2, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 2, 4, 1, 1, 1, 1, 4, 4, 4, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 4, 4, 3, 1, 1, 1, 4, 2, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 4, 4, 3, 1, 1, 1, 4, 4, 2, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 4, 4, 3, 1, 1, 1, 4, 4, 2, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 2, 4, 3, 1, 1, 1, 4, 4, 2, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 4, 4, 3, 1, 1, 1, 4, 2, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 4, 4, 3, 1, 1, 1, 4, 2, 4, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 4, 4, 3, 1, 1, 1, 4, 4, 2, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 4, 4, 3, 1, 1, 1, 4, 4, 2, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 2, 4, 3, 1, 1, 1, 4, 2, 4, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 4, 4, 3, 1, 1, 1, 4, 2, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 4, 4, 1, 1, 1, 1, 4, 4, 2, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 4, 4, 3, 1, 1, 1, 4, 4, 2, B, B, B, B, B, B, B}};
char wyvTail[BIG_DRAW_SIZE][BIG_DRAW_SIZE] = {{B, B, B, B, B, B, B, 4, 4, 4, 1, 1, 1, 1, 3, 2, 4, 2, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, 4, 4, 4, 1, 1, 1, 1, 3, 2, 4, 2, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, 4, 3, 4, 1, 1, 1, 2, 2, 2, 2, 2, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 4, 3, 4, 1, 1, 1, 2, 4, 2, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 2, 4, 4, 1, 1, 1, 2, 4, 2, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 4, 3, 4, 1, 1, 1, 2, 2, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 4, 3, 4, 1, 1, 1, 2, 4, 2, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 2, 4, 4, 1, 1, 1, 2, 4, 2, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 4, 3, 4, 1, 3, 4, 2, 2, 2, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, B, 4, 3, 4, 1, 1, 4, 4, 2, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, B, 2, 4, 4, 1, 3, 4, 4, 2, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, B, 4, 3, 4, 1, 3, 4, 2, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, B, 4, 3, 4, 1, 3, 4, 4, 2, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, B, 4, 4, 4, 1, 3, 4, 4, 2, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, B, 4, 4, 4, 1, 4, 2, 2, 2, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, B, 4, 3, 4, 1, 4, 4, 2, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, B, 4, 4, 4, 1, 4, 4, 2, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, B, 4, 4, 4, 1, 4, 2, 3, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, B, 4, 3, 4, 1, 4, 4, 2, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, B, 4, 4, 4, 1, 4, 4, 2, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, B, 4, 4, 4, 1, 4, 2, 3, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, B, 4, 4, 3, 1, 4, 4, 2, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, B, 4, 2, 4, 1, 4, 4, 2, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, B, 4, 4, 3, 4, 2, 2, 2, B, B, B, B, B, B, B, B}};
char wyvTurn[BIG_DRAW_SIZE][BIG_DRAW_SIZE] = {{B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, B, 4, 4, 4, 2, 4, 4, 4, 4, 2, 4, 4, 4, 2, 4, 4},
                                              {B, B, B, B, B, B, B, B, 4, 4, 3, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4},
                                              {B, B, B, B, B, B, B, B, 4, 4, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3},
                                              {B, B, B, B, B, B, B, B, 2, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
                                              {B, B, B, B, B, B, B, B, 4, 4, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
                                              {B, B, B, B, B, B, B, B, 4, 4, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
                                              {B, B, B, B, B, B, B, B, 4, 4, 3, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4},
                                              {B, B, B, B, B, B, B, B, 2, 4, 3, 1, 1, 1, 4, 4, 2, 2, 4, 4, 2, 2, 4, 4},
                                              {B, B, B, B, B, B, B, B, 4, 4, 3, 1, 1, 1, 4, 2, 2, 4, 2, 2, B, 4, 2, 2},
                                              {B, B, B, B, B, B, B, B, 4, 4, 3, 1, 1, 1, 4, 2, 4, 2, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 4, 4, 3, 1, 1, 1, 4, 4, 2, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 4, 4, 3, 1, 1, 1, 4, 4, 2, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 2, 4, 3, 1, 1, 1, 4, 2, 4, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 4, 4, 3, 1, 1, 1, 4, 2, B, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 4, 4, 1, 1, 1, 1, 4, 4, 2, B, B, B, B, B, B, B},
                                              {B, B, B, B, B, B, B, B, 4, 4, 3, 1, 1, 1, 4, 4, 2, B, B, B, B, B, B, B}};
HexColor guideColorMap[] = {0x00000000, 0xff3b2613, 0xffd17132, 0xff914f18, 0xff5f6667, 0xfffca480, 0xffa6a581, 0xff80a0d7, 0xfff1f1f1};
char guide[BIG_DRAW_SIZE][BIG_DRAW_SIZE] = {{B, B, B, B, B, B, B, B, B, B, B, 1, 1, B, B, 1, 1, B, B, B, B, B, B, B},
                                            {B, B, B, B, B, B, B, B, B, B, B, 1, 1, B, B, 1, 1, B, B, B, B, B, B, B},
                                            {B, B, B, B, B, B, B, B, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, B, B, B, B},
                                            {B, B, B, B, B, B, B, 1, 3, 3, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, B, B, B, B},
                                            {B, B, B, B, B, B, 1, 1, 3, 3, 1, 2, 2, 1, 1, 2, 1, 2, 1, 1, B, B, B, B},
                                            {B, B, B, B, B, B, 1, 3, 2, 2, 3, 1, 2, 1, 1, 2, 1, 1, 2, 2, B, B, B, B},
                                            {B, B, B, B, B, B, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, B, B, B, B},
                                            {B, B, B, B, B, B, B, 1, 3, 3, 2, 1, 8, 1, 1, 2, 1, B, 1, 1, B, B, B, B},
                                            {B, B, B, B, B, B, B, 1, 1, 1, 2, 2, 8, 1, 4, 2, 1, B, B, B, B, B, B, B},
                                            {B, B, B, B, B, B, B, 1, 1, 1, 2, 2, 5, 2, 2, 2, 5, 1, B, B, B, B, B, B},
                                            {B, B, B, B, B, B, 1, 6, 6, 6, 1, 2, 2, 2, 2, 2, 1, B, B, B, B, B, B, B},
                                            {B, B, B, B, B, 1, 6, 6, 6, 6, 6, 1, 1, 1, 1, 1, 6, 1, B, B, B, B, B, B},
                                            {B, B, B, B, B, 1, 6, 6, 1, 1, 6, 6, 6, 4, 4, 4, 6, 1, B, B, B, B, B, B},
                                            {B, B, B, B, B, 1, 6, 6, 1, 1, 6, 6, 6, 4, 4, 6, 4, 1, B, B, B, B, B, B},
                                            {B, B, B, B, B, 1, 6, 6, 1, 1, 4, 6, 6, 6, 6, 6, 1, 1, B, B, B, B, B, B},
                                            {B, B, B, B, B, 1, 2, 3, 2, 2, 1, 4, 6, 6, 6, 6, 1, 2, 1, 1, B, B, B, B},
                                            {B, B, B, B, B, 1, 2, 2, 2, 2, 1, 4, 6, 4, 4, 6, 1, 2, 1, 1, B, B, B, B},
                                            {B, B, B, B, B, 1, 2, 2, 2, 2, 1, 6, 6, 4, 4, 6, 1, 2, 1, 1, B, B, B, B},
                                            {B, B, B, B, B, B, 1, 1, 1, 1, 4, 4, 7, 1, 1, 7, 1, 1, B, B, B, B, B, B},
                                            {B, B, B, B, B, B, B, B, 1, 4, 4, 4, 7, 1, 4, 7, 1, B, B, B, B, B, B, B},
                                            {B, B, B, B, B, B, B, 1, 4, 4, 4, 4, 4, 1, 1, 4, 1, B, B, B, B, B, B, B},
                                            {B, B, B, B, B, B, B, 1, 4, 4, 4, 4, 1, 1, 1, 1, 1, B, B, B, B, B, B, B},
                                            {B, B, B, B, B, B, B, 1, 4, 4, 4, 1, 1, 4, 4, 1, 4, 1, B, B, B, B, B, B},
                                            {B, B, B, B, B, B, B, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, B, B, B, B, B, B}};